### ISSUE TITLE
Separated letters

### ISSUE THREAD

**Issue by kjellouli** [silnrsi/font-lateef#1]
Hello !
First of all, I would like to thank you for your great efforts in working out this new version of Lateef.
However, when using it, it seems the letters are separated (see attachment below). The Lateef font is mainly used on the http://Quranindex.info website. Would you have an idea what is causing the issue ?

Thank you very much for your consideration,
Kamal J.

![image](https://cloud.githubusercontent.com/assets/6676571/24429809/afa6bcdc-13e1-11e7-9d0d-171dc48e7cb0.png)
![image](https://cloud.githubusercontent.com/assets/6676571/24429836/c4104800-13e1-11e7-8579-e986b39d55c9.png)

**Comment by LornaSIL** [comment]
At this point "LateefGR" is a Graphite-only font. It should display properly on Firefox, but it will not display properly on any other browser. You may continue to use the old (OpenType) Lateef font (v 1.001) until we are able to add OpenType into version 1.200.

**Comment by bobh0303** [comment]
If you try Firefox and find it does not work with LateefGR, feel free to reopen this issue.
