### ISSUE TITLE
The kashida character is the incorrect thickness for non-regular weights

### ISSUE THREAD

**Issue by amarz45** [silnrsi/font-lateef#3]
The kashida Unicode character (U+0640) is used for elongation for justification in Arabic. For this font, it looks fine for the regular weight. However, for the Light and ExtraLight weights it looks too thick and for the Bold, SemiBold, and ExtraBold weights it looks too thin. The following image is an example with the ExtraLight weight.

![import-2023-01-28_13:21:58](https://user-images.githubusercontent.com/92645199/215284272-3eb5587d-2017-4b80-a216-9e990332b627.png)

I think this is because the kashida character is only designed for the regular weight. This can probably be fixed by adjusting it for these weights.

**Comment by LornaSIL** [comment]
Thanks for this report. We will definitely want to fix this.

**Comment by LornaSIL** [comment]
I have verified that this was the behavior for the released v2.000. We've fixed it in our development version. When we release a new version it should be okay.

**Comment by LornaSIL** [comment]
This issue has been fixed in the new v4.000 release.
