### ISSUE TITLE
Add Arabic honorifics

### ISSUE THREAD

**Issue by amarz45** [silnrsi/font-lateef#4]
Can you add the following Arabic honorifics:

- U+FDFE (سبحانه وتعالى)
- U+FDFF (عز وجل)
- U+FD40 (رحمه الله)
- U+FD41 (رضي الله عنه)
- U+FD42 (رضي الله عنها)
- U+FD43 (رضي الله عنهم)
- U+FD44 (رضي الله عنهما)
- U+FD45 (رضي الله عنهن)
- U+FD47 (عليه السلام)
- U+FD4D (عليها السلام)
- U+FD48 (عليهم السلام)
- U+FD49 (عليهما السلام)

And additionally U+FDFD (﷽)?

**Comment by LornaSIL** [comment]
We added all of these to Scheherazade New. https://software.sil.org/scheherazade/download/
Perhaps you could switch to that font for just the honorifics?

At this point I don't think we have the design resources to also add these to Lateef, but I'll add your request to the list.

**Comment by LornaSIL** [comment]
We've just updated Lateef and added FD42, FD47, and FDFD. You can download the new version here: https://software.sil.org/lateef/download/

I will add your request for the others to our issues, however, we do not currently have planns to add them to Lateef. As noted above, you may use Scheherazade New which does have all the honorifics.
